name: Testing

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore:
      - '**.md'
      - 'docs/**'

permissions:
  contents: read
  id-token: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: [team-flutter]
    outputs:
      version: ${{ steps.meta.outputs.version }}
      version-title: ${{ steps.meta.outputs.version-title }}
    steps:
      - uses: AdGuardSoftwareLimited/actions/actions/epoch-version-metadata@master
        id: meta

  check-fixme:
    uses: AdGuardSoftwareLimited/actions/.github/workflows/check-fixme.yml@master
    with:
      team: flutter

  build-android:
    needs: [prepare]
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/flutter-build-android.yml
    secrets: inherit
    with:
      version: ${{ needs.prepare.outputs.version }}
      build-number: ${{ github.run_number }}
      artifact-name: mfa-android-pr
      artifact-path: example/build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    needs: [prepare]
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/flutter-build-ios.yml
    secrets: inherit
    with:
      version: ${{ needs.prepare.outputs.version }}
      build-number: ${{ github.run_number }}
      artifact-name: mfa-ios-pr
      artifact-path: example/build/ios/iphoneos/Runner.app

  build-macos:
    needs: [prepare]
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/flutter-build-macos.yml
    secrets: inherit
    with:
      version: ${{ needs.prepare.outputs.version }}
      build-number: ${{ github.run_number }}
      artifact-name: mfa-macos-pr
      artifact-path: example/build/macos/Build/Products/Release/*.app

  build-windows:
    needs: [prepare]
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/flutter-build-windows.yml
    secrets: inherit
    with:
      version: ${{ needs.prepare.outputs.version }}
      build-number: ${{ github.run_number }}
      artifact-name: mfa-windows-pr
      artifact-path: |
        example/build/windows/x64/runner/Release/*
        example/build/windows/x64/runner/msix/*.msix
